### ISSUE TITLE
[MU4 Issue] crash closing mixer

### ISSUE THREAD

**Issue by lyrra** [musescore/MuseScore#13141]
1) select a note
2) close mixer
3) crash

gdb backtrace:
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff6cc384a0e in deto::async::Channel<unsigned char, mu::audio::AudioSignalVal>::ChannelInvoker::doInvoke (this=0x169e6cd2810, callKey=0x1, call=0x169e5af44a0, d=...) at src/framework/global/thirdparty/deto_async/async/channel.h:126
126                     static_cast<IReceive*>(call)->received(d);
(gdb) ba
#0  0x00007ff6cc384a0e in deto::async::Channel<unsigned char, mu::audio::AudioSignalVal>::ChannelInvoker::doInvoke (this=0x169e6cd2810, callKey=0x1, call=0x169e5af44a0, d=...) at src/framework/global/thirdparty/deto_async/async/channel.h:126
#1  0x00007ff6cb33372c in deto::async::AbstractInvoker::invokeCallback (this=0x169e6cd2810, type=0x1, c=..., data=...) at src/framework/global/thirdparty/deto_async/async/internal/abstractinvoker.cpp:61
#2  0x00007ff6cc3790cc in deto::async::AbstractInvoker::QInvoker::invoke (this=0x169e9bf5ef0) at src/framework/global/thirdparty/deto_async/async/internal/abstractinvoker.h:134
#3  0x00007ff6cb333386 in operator() (__closure=0x169e31cd7d0) at src/framework/global/thirdparty/deto_async/async/internal/abstractinvoker.cpp:48
#4  0x00007ff6cb33cf78 in std::__invoke_impl<void, deto::async::AbstractInvoker::invoke(int, const deto::async::NotifyData&)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /mingw64/include/c++/12.1.0/bits/invoke.h:61
#5  0x00007ff6cb33c6c8 in std::__invoke_r<void, deto::async::AbstractInvoker::invoke(int, const deto::async::NotifyData&)::<lambda()>&>(struct {...} &) (__fn=...) at /mingw64/include/c++/12.1.0/bits/invoke.h:111
#6  0x00007ff6cb33c242 in std::_Function_handler<void(), deto::async::AbstractInvoker::invoke(int, const deto::async::NotifyData&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /mingw64/include/c++/12.1.0/bits/std_function.h:290
#7  0x00007ff6cc5b1252 in std::function<void ()>::operator()() const (this=0x169e31cd7d0) at /mingw64/include/c++/12.1.0/bits/std_function.h:591
#8  0x00007ff6cc0dc41b in mu::framework::Invoker::doInvoke (this=0x7ff6ce579580 <s_asyncInvoker>, ptr=0x169e31cd7d0) at src/framework/global/internal/invoker.cpp:57
#9  0x00007ff6cc0e0005 in mu::framework::Invoker::qt_static_metacall (_o=0x7ff6ce579580 <s_asyncInvoker>, _c=QMetaObject::InvokeMetaMethod, _id=0x0, _a=0x169ea0604c8) at builds/Win-Qt--Make-Debug/src/framework/global/global_autogen/EGDWYGFDBT/moc_invoker.cpp:73
#10 0x00007ffa5727371c in QObject::event(QEvent*) () from builds\Win-Qt--Make-Debug\install\bin\Qt5Core.dll
#11 0x00007ffa55257ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from builds\Win-Qt--Make-Debug\install\bin\Qt5Widgets.dll
#12 0x00007ffa5724629d in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from builds\Win-Qt--Make-Debug\install\bin\Qt5Core.dll
#13 0x00007ffa5724c83b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from builds\Win-Qt--Make-Debug\install\bin\Qt5Core.dll

tested at commit bdce152

Possible related issues:
- https://github.com/musescore/MuseScore/issues/12815
- https://github.com/musescore/MuseScore/issues/12549
- https://github.com/musescore/MuseScore/issues/9467

**Comment by lyrra** [comment]
closing, duplicate of https://github.com/musescore/MuseScore/issues/9467
