### ISSUE TITLE
[MU4 Issue] Muse Hub installer crashes the Windows desktop environment

### ISSUE THREAD

**Issue by deltz025** [musescore/MuseScore#13882]
**Describe the bug**
The installer threw up an error, and then crashed, along with the Windows desktop environment. Upon a reboot, the Hub app was installed, and appears to function properly. See log file for details. 

**To Reproduce**
1. Download and extract the Muse Hub Windows installer
2. Run the installer

**Expected behavior**
Muse Hub should install graphically. 

**Platform information**
Edition: Windows 10 Home
Version: 21H2
OS build: 19044.2130
Experience: Windows Feature Experience Pack 120.2212.4180.0

**Additional context**
Snippet from log file:

```
2022-10-22 17:45:26.3928|INFO|Muse.App|Attempting to set the users language to en-US using file C:\Program Files\WindowsApps\Muse.MuseHub_0.9.6.484_x64__rb9pth70m6nz6\Assets\Strings\en-US\Localizable.strings
2022-10-22 17:45:27.0314|ERROR|Muse.App|Startup Error: The method or operation is not implemented.|System.NotImplementedException: The method or operation is not implemented.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Windowing.IAppWindowMethods.set_IsShownInSwitchers(IObjectReference _obj, Boolean value)
   at Microsoft.UI.Windowing.AppWindow.set_IsShownInSwitchers(Boolean value)
   at Muse.MuseWindow..ctor() in D:\a\Muse\Muse\Windows\src\Muse\MuseWindow.cs:line 42
   at Muse.App.<>c__DisplayClass16_0.<OnActivated>b__0() in D:\a\Muse\Muse\Windows\src\Muse\App.xaml.cs:line 145

```

[client_log.txt](https://github.com/musescore/MuseScore/files/9845377/client_log.txt)
[Specifications.txt](https://github.com/musescore/MuseScore/files/9845378/Specifications.txt)

**Comment by eg0n1984** [comment]
I confirm same behavior:
Edição	Windows 10 Pro
Versão	21H2
19044.2075
Windows Feature Experience Pack 120.2212.4180.0

**Comment by Tantacrul** [comment]
@deltz025  - how are things now? Since you logged this issue, there have been quite a few improvements.
