### ISSUE TITLE
[MuseHub Issue] crash while downloading strings library

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#13967]
**Describe the bug**
During downloading strings library, MuseHub crashed. Downloading continued at background.

**To Reproduce**
1. Open MuseHub
2. Download Strings library
3. After some time, MuseHub crashes

**Expected behavior**
No crash

**Screenshots**

https://user-images.githubusercontent.com/1646034/197510884-80c081d4-89a5-41ae-9afa-3a794cf33bb9.mp4

**Platform information**
 - OS: [reported on Linux]
Ubuntu Studio 22.04 KDE Plasma

**Additional context**
Downloading process continues at background, even if MuseHub is closed after crash.

**Comment by Tantacrul** [comment]
@sammik - same question

**Comment by sammik** [comment]
@Tantacrul 
Still the same

here is terminal output: <details>
muse-hub
2022-11-10 17:07:34.5958|INFO|Muse.Client.Linux.App|Attempting to set the users language to en-US using file /opt/muse-hub/Assets/Strings/en-US/Localizable.strings
2022-11-10 17:07:35.8826|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:35.8826|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:35.8826|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:35.9091|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:35.9091|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:35.9091|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:35.9375|INFO|Muse.Client.Common.Services.MuseBackgroundService|Attempting to connect to background service (starting background thread)...
2022-11-10 17:07:35.9498|INFO|Muse.Client.Common.Services.MuseBackgroundService|Connected to the muse service
2022-11-10 17:07:36.1531|INFO|Muse.Client.Common.Services.MuseBackgroundService|Received message from background service - Type: Muse.Common.Messages.Actions.UpdateAppStateAction, Data: -
2022-11-10 17:07:36.1579|DEBUG|Muse.Common.Services.MuseHubStateManager|Syncing State...
2022-11-10 17:07:36.3860|INFO|Muse.Client.Common.Services.UpdateManager|Checking for updates...
2022-11-10 17:07:36.3926|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:36.3928|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:36.4026|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:36.4026|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:36.4130|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:36.4130|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2022-11-10 17:07:36.9860|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 1073.7705ms - 200
2022-11-10 17:07:36.9906|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 1121.6366ms - 200
2022-11-10 17:07:37.3760|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 962.7492ms - 200
2022-11-10 17:07:37.3760|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 963.2907ms - 200
2022-11-10 17:07:37.4068|INFO|Muse.Client.Common.Services.MuseBackgroundService|Sending message to background service - Type: Muse.Common.Messages.Actions.RegisterHiddenDownloadAction, Data: ItemId=musesampler;ItemType=Application;P2PInfoFile=https://muse-webservice.azurewebsites.net/musedownload/application-builds/dc02a17f-f3bc-4035-8acb-e08c341db510?entity=applicationLinuxVersion&entity-id=53df157d-e2f3-47cf-815a-40730cd6cc8f;Version=0.2.4.7;ItemName=MuseSampler
2022-11-10 17:07:37.4320|INFO|Muse.Client.Common.Services.MuseBackgroundService|Sending message to background service - Type: Muse.Common.Messages.Actions.RegisterHiddenDownloadAction, Data: ItemId=hub;ItemType=Application;P2PInfoFile=https://muse-webservice.azurewebsites.net/musedownload/application-builds/166bf15f-0a20-4c81-9990-b6c13901f41d?entity=applicationLinuxVersion&entity-id=8ff711c9-7d78-4d93-a9b5-ad3b934b63b5;Version=0.9.9.295;ItemName=Muse Hub
2022-11-10 17:07:38.7357|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 2332.8467ms - 200
2022-11-10 17:07:38.7366|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 2334.0424ms - 200
2022-11-10 17:07:38.7529|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 2843.5693ms - 200
2022-11-10 17:07:38.7529|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 2884.4698ms - 200
2022-11-10 17:07:38.7529|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 2844.1568ms - 200
2022-11-10 17:07:38.7529|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 2884.9775ms - 200
2022-11-10 17:07:38.9194|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 2526.4954ms - 200
2022-11-10 17:07:38.9194|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 2527.0373ms - 200
2022-11-10 17:07:47.8397|INFO|Muse.Client.Common.Services.MuseBackgroundService|Sending message to background service - Type: Muse.Common.Messages.Actions.StartDownloadAction, Data: ItemId=c242d818-4654-41f6-8659-a8d0f5c9232b;ItemType=Instrument;P2PInfoFile=https://muse-webservice.azurewebsites.net/musedownload/library-packages/c37add97-58a2-4b8e-ad16-d2c7572409fb?entity=libraryVersion&entity-id=1b599c49-84d8-4d24-8a5e-dbd3ae4b6fa2;Version=0.4.0;ItemName=Muse Strings
2022-11-10 17:07:47.8526|DEBUG|Muse.Client.Common.Services.MuseBackgroundService|Received message from background service - Type: Muse.Common.Messages.DownloadStatusMessage, Data: -
2022-11-10 17:07:47.8576|DEBUG|Muse.Common.Services.MuseHubStateManager|Updating Item State: Type: Instrument, Id: c242d818-4654-41f6-8659-a8d0f5c9232b, Name: Muse Strings, Version: 0.4.0, Progress: 0, State: Downloading, BPS: 0, Seconds Remaining: 0
2022-11-10 17:07:49.4631|DEBUG|Muse.Client.Common.Services.MuseBackgroundService|Received message from background service - Type: Muse.Common.Messages.DownloadStatusMessage, Data: -
2022-11-10 17:07:49.4631|DEBUG|Muse.Common.Services.MuseHubStateManager|Updating Item State: Type: Instrument, Id: c242d818-4654-41f6-8659-a8d0f5c9232b, Name: Muse Strings, Version: 0.4.0, Progress: 0, State: Downloading, BPS: 0, Seconds Remaining: 0
2022-11-10 17:07:49.6328|DEBUG|Muse.Client.Common.Services.MuseBackgroundService|Received message from background service - Type: Muse.Common.Messages.DownloadStatusMessage, Data: -
2022-11-10 17:07:49.6328|DEBUG|Muse.Common.Services.MuseHubStateManager|Updating Item State: Type: Instrument, Id: c242d818-4654-41f6-8659-a8d0f5c9232b, Name: Muse Strings, Version: 0.4.0, Progress: 0, State: Downloading, BPS: 0, Seconds Remaining: 1E+09
Unhandled exception. System.ArgumentException: The resource object with key 'TimeSpanHumanize_MultipleDays' was not found (Parameter 'resourceKey')
   at Humanizer.Localisation.Formatters.DefaultFormatter.Format(String resourceKey, Int32 number, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 137
   at Humanizer.Localisation.Formatters.DefaultFormatter.GetResourceForTimeSpan(TimeUnit unit, Int32 count, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 102
   at Humanizer.Localisation.Formatters.DefaultFormatter.TimeSpanHumanize(TimeUnit timeUnit, Int32 unit, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 71
   at Humanizer.TimeSpanHumanizeExtensions.CreateTheTimePartsWithUpperAndLowerLimits(TimeSpan timespan, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 63
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, Boolean countEmptyUnits, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, String collectionSeparator, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 50
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, String collectionSeparator, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 33
   at Muse.Client.Common.ViewModels.MainViewModel.UpdateStatusPanel() in /home/runner/work/Muse/Muse/WindowsLinuxCommon/src/Muse.Client.Common/ViewModels/MainViewModel.cs:line 245
   at Muse.Client.Common.ViewModels.MainViewModel.<MuseHubStateManager_StateChanged>b__51_0() in /home/runner/work/Muse/Muse/WindowsLinuxCommon/src/Muse.Client.Common/ViewModels/MainViewModel.cs:line 230
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
--- End of stack trace from previous location ---
   at Muse.Client.Linux.Services.LinuxDispatcherService.RunOnUIThreadAsync(Action action) in /home/runner/work/Muse/Muse/Linux/src/Muse.Client.Linux/Services/LinuxDispatcherService.cs:line 10
   at Muse.Client.Common.ViewModels.MainViewModel.MuseHubStateManager_StateChanged(Object sender, EventArgs e) in /home/runner/work/Muse/Muse/WindowsLinuxCommon/src/Muse.Client.Common/ViewModels/MainViewModel.cs:line 230
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)
</details>

**Comment by iamtesch** [comment]
This should be resolved with hub release 0.9.10; can you verify if this is resolved now?

**Comment by sammik** [comment]
@iamtesch seems to be fixed here, thank you!

**Comment by iamtesch** [comment]
Awesome - thanks!
