### ISSUE TITLE
[MU4 Issue] Crash when extract all parts from some old big scores 

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14058]
**To Reproduce**
1. Open [Test..._Beethoven__Symphony_No._9__Op._125.zip](https://github.com/musescore/MuseScore/files/9869040/Test._Beethoven__Symphony_No._9__Op._125.zip) or [Gluck_-_Iphignie_en_Aulide__Vocal_Score.zip](https://github.com/musescore/MuseScore/files/9869044/Gluck_-_Iphignie_en_Aulide__Vocal_Score.zip)
2. Open Parts
3. Open all

https://user-images.githubusercontent.com/90187801/198017105-941fe50b-7db0-476c-b212-65754f13a79a.mp4

**Platform information**
macOS, Windows

**Additional context**

**Comment by lyrra** [comment]
Shrinked that gigantic mscz file into this mscx, crashes with the same backtrace which suggest same bug is triggered

```
<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.00">
  <Score>
    <Part id="1">
      <Staff id="1"> </Staff>
      </Part>
    <Staff id="1">
      <TBox> </TBox>
      <Measure>
        </Measure>
      </Staff>
    </Score>
  </museScore>
```

<details><summary>backtrace</summary>

```
Backtrace from original mscx file:
#0  0x00005555559b67d0 in mu::engraving::MeasureBase::prev (this=0x0) at src/engraving/libmscore/measurebase.h:112
#1  0x00005555559960e4 in mu::engraving::MeasureBaseList::fixupSystems (this=0x5555ba02c9f0) at src/engraving/libmscore/score.cpp:296
#2  0x0000555555995de8 in mu::engraving::MeasureBaseList::insert (this=0x5555ba02c9f0, fm=0x5555b5bd3a60, lm=0x5555b5bd3a60) at src/engraving/libmscore/score.cpp:227
#3  0x0000555555af7f68 in mu::engraving::InsertRemoveMeasures::insertMeasures ( this=0x5555b5bd3c10) at src/engraving/libmscore/undo.cpp:2041
#4  0x0000555555cdb1a2 in mu::engraving::InsertMeasures::redo (this=0x5555b5bd3c10) at src/engraving/libmscore/undo.h:913
#5  0x0000555555af0d29 in mu::engraving::UndoStack::push (this=0x55555ae4a250, cmd=0x5555b5bd3c10, ed=0x0) at src/engraving/libmscore/undo.cpp:354
#6  0x00005555559a8e2b in mu::engraving::Score::undo (this=0x5555ba02c490, cmd=0x5555b5bd3c10, ed=0x0) at src/engraving/libmscore/score.cpp:4165
#7  0x0000555555cc7897 in mu::engraving::Score::insertMeasure (this=0x5555ba02c490, type, beforeMeasure=0x5555ba995dd0, options=...) at src/engraving/libmscore/edit.cpp:3734
#8  0x0000555555cfec5a in mu::engraving::Excerpt::createExcerpt (excerpt=0x5555ad01dc40) at src/engraving/libmscore/excerpt.cpp:329
#9  0x0000555555cffd5d in mu::engraving::MasterScore::initExcerpt (this=0x55555cf9b590, excerpt=0x5555ad01dc40) at src/engraving/libmscore/excerpt.cpp:510
#10 0x0000555555cffbe5 in mu::engraving::MasterScore::initAndAddExcerpt (this=0x55555cf9b590, excerpt=0x5555ad01dc40, fakeUndo=false) at src/engraving/libmscore/excerpt.cpp:488
#11 0x000055555626cde0 in mu::notation::MasterNotation::addExcerpts (this=0x55555ba8fa50, excerpts) at src/notation/internal/masternotation.cpp:460
#12 0x00005555564a59f7 in mu::notation::PartListModel::openNotations (this=0x5555ad02f1c0, rows=...) at src/notation/view/partlistmodel.cpp:262
#13 0x00005555564a589b in mu::notation::PartListModel::openAllParts (this=0x5555ad02f1c0) at src/notation/view/partlistmodel.cpp:248

Backtrace from above minimization:
#0  0x00005555559b67d0 in mu::engraving::MeasureBase::prev (this=0x0) at src/engraving/libmscore/measurebase.h:112
#1  0x00005555559960e4 in mu::engraving::MeasureBaseList::fixupSystems (this=0x55556014ead0) at src/engraving/libmscore/score.cpp:296
#2  0x0000555555995de8 in mu::engraving::MeasureBaseList::insert (this=0x55556014ead0, fm=0x55555ac38620, lm=0x55555ac38620) at src/engraving/libmscore/score.cpp:227
#3  0x0000555555af7f68 in mu::engraving::InsertRemoveMeasures::insertMeasures (this=0x55555c65e2b0) at src/engraving/libmscore/undo.cpp:2041 
#4  0x0000555555cdb1a2 in mu::engraving::InsertMeasures::redo (this=0x55555c65e2b0) at src/engraving/libmscore/undo.h:913
#5  0x0000555555af0d29 in mu::engraving::UndoStack::push (this=0x55555c37b7b0, cmd=0x55555c65e2b0, ed=0x0) at src/engraving/libmscore/undo.cpp:354
#6  0x00005555559a8e2b in mu::engraving::Score::undo (this=0x55556014e570, cmd=0x55555c65e2b0, ed=0x0) at src/engraving/libmscore/score.cpp:4165
#7  0x0000555555cc7897 in mu::engraving::Score::insertMeasure (this=0x55556014e570, type=mu::engraving::ElementType::VBOX, beforeMeasure=0x55555d594a20, options=...) at src/engraving/libmscore/edit.cpp:3734
#8  0x0000555555cfec5a in mu::engraving::Excerpt::createExcerpt (excerpt=0x55555ae70650) at src/engraving/libmscore/excerpt.cpp:329
#9  0x0000555555cffd5d in mu::engraving::MasterScore::initExcerpt (this=0x55555d32f050, excerpt=0x55555ae70650) at src/engraving/libmscore/excerpt.cpp:510
#10 0x0000555555cffbe5 in mu::engraving::MasterScore::initAndAddExcerpt (this=0x55555d32f050, excerpt=0x55555ae70650, fakeUndo=false) at src/engraving/libmscore/excerpt.cpp:488
```
</details>
