### ISSUE TITLE
[MU4] Muse Hub crashes when wanting to open UI on Windows 10

### ISSUE THREAD

**Issue by pandenista** [musescore/MuseScore#14131]
First I run Muse Hub it was OK, I intstalled MS 4 and String Muse Sound. Then I wanted to change target location. Nothing happened, so I returned to default settings. Then Muse Hub started to crash just after I dragged my mouse over the icon of Muse Hub.

Additional info from Event viewer:

Application: Muse.exe
CoreCLR Version: 6.0.1022.47605
.NET Version: 6.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: The resource object with key 'TimeSpanHumanize_MultipleDays' was not found (Parameter 'resourceKey')
   at Humanizer.Localisation.Formatters.DefaultFormatter.Format(String resourceKey, Int32 number, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 137
   at Humanizer.Localisation.Formatters.DefaultFormatter.GetResourceForTimeSpan(TimeUnit unit, Int32 count, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 102
   at Humanizer.Localisation.Formatters.DefaultFormatter.TimeSpanHumanize(TimeUnit timeUnit, Int32 unit, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 71
   at Humanizer.TimeSpanHumanizeExtensions.CreateTheTimePartsWithUpperAndLowerLimits(TimeSpan timespan, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 63
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, Boolean countEmptyUnits, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, String collectionSeparator, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 50
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, String collectionSeparator, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 33
   at Muse.Client.Common.ViewModels.MainViewModel.UpdateStatusPanel() in D:\a\Muse\Muse\WindowsLinuxCommon\src\Muse.Client.Common\ViewModels\MainViewModel.cs:line 245
   at Muse.Client.Common.ViewModels.MainViewModel.<MuseHubStateManager_StateChanged>b__51_0() in D:\a\Muse\Muse\WindowsLinuxCommon\src\Muse.Client.Common\ViewModels\MainViewModel.cs:line 230
   at CommunityToolkit.WinUI.DispatcherQueueExtensions.<>c__DisplayClass0_0.<EnqueueAsync>b__1()
--- End of stack trace from previous location ---
   at Muse.Services.WindowsDispatcherService.RunOnUIThreadAsync(Action action) in D:\a\Muse\Muse\Windows\src\Muse\Services\WindowsDispatcherService.cs:line 20
   at Muse.Client.Common.ViewModels.MainViewModel.MuseHubStateManager_StateChanged(Object sender, EventArgs e) in D:\a\Muse\Muse\WindowsLinuxCommon\src\Muse.Client.Common\ViewModels\MainViewModel.cs:line 230
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by iamtesch** [comment]
Can you uninstall and then reinstall the latest version from musehub.com?  There was a bug when setting the target folder that should be resolved now.

**Comment by pandenista** [comment]
I did it just as you wrote. The new version doesn't start, now with this exception:

Application: Muse.exe
CoreCLR Version: 6.0.1122.52304
.NET Version: 6.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: The resource object with key 'TimeSpanHumanize_MultipleDays' was not found (Parameter 'resourceKey')
   at Humanizer.Localisation.Formatters.DefaultFormatter.Format(String resourceKey, Int32 number, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 137
   at Humanizer.Localisation.Formatters.DefaultFormatter.GetResourceForTimeSpan(TimeUnit unit, Int32 count, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 102
   at Humanizer.Localisation.Formatters.DefaultFormatter.TimeSpanHumanize(TimeUnit timeUnit, Int32 unit, Boolean toWords) in /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:line 71
   at Humanizer.TimeSpanHumanizeExtensions.CreateTheTimePartsWithUpperAndLowerLimits(TimeSpan timespan, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 63
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, Boolean countEmptyUnits, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, String collectionSeparator, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 50
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, String collectionSeparator, Boolean toWords) in /_/src/Humanizer/TimeSpanHumanizeExtensions.cs:line 33
   at Muse.Client.Common.ViewModels.MainViewModel.UpdateStatusPanel() in D:\a\Muse\Muse\WindowsLinuxCommon\src\Muse.Client.Common\ViewModels\MainViewModel.cs:line 245
   at Muse.Client.Common.ViewModels.MainViewModel.<MuseHubStateManager_StateChanged>b__51_0() in D:\a\Muse\Muse\WindowsLinuxCommon\src\Muse.Client.Common\ViewModels\MainViewModel.cs:line 230
   at CommunityToolkit.WinUI.DispatcherQueueExtensions.<>c__DisplayClass0_0.<EnqueueAsync>b__1()
--- End of stack trace from previous location ---
   at Muse.Services.WindowsDispatcherService.RunOnUIThreadAsync(Action action) in D:\a\Muse\Muse\Windows\src\Muse\Services\WindowsDispatcherService.cs:line 20
   at Muse.Client.Common.ViewModels.MainViewModel.MuseHubStateManager_StateChanged(Object sender, EventArgs e) in D:\a\Muse\Muse\WindowsLinuxCommon\src\Muse.Client.Common\ViewModels\MainViewModel.cs:line 230
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by finwe** [comment]
Getting the same crash, my Windows are in Czech localization.

**Comment by pandenista** [comment]
Yes, my Windows are Czech.

Získat Outlook pro Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by finwe** [comment]
There is also an according Issue in Humanizer itself https://github.com/Humanizr/Humanizer/issues/814 more than 3 years old.

**Comment by DominicMaas** [comment]
Hi, can you give this a try using the latest version of Muse Hub? You may need to download it manually. 

Should now be fixed.

**Comment by finwe** [comment]
I installed the last version after uninstalling all Muse apps and I now cannot even run/use Muse Hub. The process runs in the background, but the tray icon cannot be seen. Trying to run the installer once more causes it to crash. Reinstalling completely does not help either and there are no helpful information in event viewer either.

**Comment by pandenista** [comment]
In my case, when I reintalled MuseHub with the new version, the bug seems to be resolved, MuseHub UI starts and even can be activated from tray icon. Thanks.
Martin.

Získat Outlook pro Android<https://aka.ms/AAb9ysg>
________________________________
