### ISSUE TITLE
[MU4 Issue] This particular score crashes

### ISSUE THREAD

**Issue by woooowoooo** [musescore/MuseScore#14355]
**Describe the bug**
I have no idea why this score crashes, but it does. I've isolated this section in particular and the only notable thing about it is that it uses multiple voices.

**To Reproduce**
1. Rename the score from .zip to .mscz
2. Open it. MS 4 crashes.

**Expected behavior**
It does not crash.

**Platform information**
 - OS: Linux Mint 20.3 Cinnamon

**Comment by DaddyLudwig** [comment]
Uh, I don't see a score.

**Comment by woooowoooo** [comment]
just realized I did not attach the offending score 
[Test 1.zip](https://github.com/musescore/MuseScore/files/9944960/Test.1.zip)

**Comment by lyrra** [comment]
reproduced crash on linux (git commit height 2c34155):
<details><summary> backtrace: </summary>

```
#0  mu::engraving::Note::layout2 (this=0x55555d64f040) at src/engraving/libmscore/note.cpp:2353
#1  0x0000555555d127ec in mu::engraving::Chord::layoutTablature (this=0x55555c25b120) at src/engraving/libmscore/chord.cpp:2639
#2  0x0000555555d0ef4c in mu::engraving::Chord::layout (this=0x55555c25b120) at src/engraving/libmscore/chord.cpp:2029
#3  0x0000555555c76bd2 in layoutSegmentElements (segment=0x55555d4e2770, startTrack=0, endTrack=4, staffIdx=0) at src/engraving/layout/layoutchords.cpp:52
#4  0x0000555555c76df9 in mu::engraving::LayoutChords::layoutChords1 (score=0x55555d9359d0, segment=0x55555d4e2770, staffIdx=0) at src/engraving/layout/layoutchords.cpp:78
#5  0x0000555555c71856 in mu::engraving::LayoutMeasure::getNextMeasure (options=..., ctx=...) at src/engraving/layout/layoutmeasure.cpp:767
#6  0x0000555555c83f1f in mu::engraving::LayoutSystem::collectSystem (options=..., ctx=..., score=0x55555d9359d0) at src/engraving/layout/layoutsystem.cpp:195
#7  0x0000555555c68ba8 in mu::engraving::Layout::doLayoutRange (this=0x55555d940d18, options=..., st=..., et=...) at src/engraving/layout/layout.cpp:217
#8  0x0000555555a1a03e in mu::engraving::Score::doLayoutRange (this=0x55555d9359d0, st=..., et=...) at src/engraving/libmscore/score.cpp:5495
#9  0x0000555555a19df2 in mu::engraving::Score::doLayout (this=0x55555d9359d0) at src/engraving/libmscore/score.cpp:5484
#10 0x0000555555a04919 in mu::engraving::Score::setIsOpen (this=0x55555d9359d0, open=true) at src/engraving/libmscore/score.cpp:881
#11 0x000055555627b0c8 in mu::notation::Notation::setIsOpen (this=0x55555c631348, open=true) at src/notation/internal/notation.cpp:223

```
</details>
<details><summary>code around crash point</summary>

```
void Note::layout2()
{
...
            double hookBottom = chord()->hook()->height() + chord()->hook()->y() + chord()->pos().y() + (0.25 * spatium());
            // the top dot in the chord, not the dot for this particular note:
            double dotY = chord()->notes().back()->y() + chord()->notes().back()->dots().front()->pos().y();  <-------------------- Line 2353
            if (chord()->dotPosX() < hookRight && dotY < hookBottom) {
                d = chord()->hook()->width();

```

</details>

<details><summary>minimized score that still reproduces same crash (.mscx format)</summary>

```
<?xml version="1.0" encoding="UTF-8"?>
<museScore version="3.02">
  <programVersion>3.6.2</programVersion>
  <programRevision></programRevision>
  <Score>
    <Division>480</Division>
    <Part>
      <Staff id="1">
        <StaffType group="tablature">
          <name>tab4StrFull</name>
          <lines>4</lines>
          </StaffType>
        <defaultClef>G8vb</defaultClef>
        </Staff>
      </Part>
    <Staff id="1">
      <Measure>
        <voice>
          <TimeSig>
            <sigN>2</sigN>
            <sigD>4</sigD>
            </TimeSig>
          <Chord>
            <dots>1</dots>
            <durationType>eighth</durationType>
            <Note>
              <pitch>65</pitch>
              <tpc>13</tpc>
              <fret>17</fret>
              <string>3</string>
              </Note>
            </Chord>
          <Chord>
            <durationType>quarter</durationType>
            <Note>
              <pitch>65</pitch>
              <tpc>13</tpc>
              <fret>17</fret>
              <string>3</string>
              </Note>
            </Chord>
          <Chord>
            <durationType>16th</durationType>
            <Note>
              <pitch>69</pitch>
              <tpc>17</tpc>
              <fret>0</fret>
              <string>0</string>
              </Note>
            </Chord>
          </voice>
        <voice>
          <Chord>
            <durationType>16th</durationType>
            <Note>
              <pitch>62</pitch>
              <tpc>16</tpc>
              <fret>7</fret>
              <string>2</string>
              </Note>
            </Chord>
          </voice>
        </Measure>
      </Staff>
    </Score>
  </museScore>

```

</details>

**Comment by cbjeukendrup** [comment]
The cause of the crash seems to be that we assume that the dot of the topmost note is already created, laid out and positioned, when positioning the dots of the other notes. But that is not the case; the notes are handled from bottom to top, so when laying out dots for the lower notes, the dot for the top note may not have been created yet, which is the case for this score.
