### ISSUE TITLE
Musescore crash if you attempt to explode meaures containing chords with different numbers of notes.

### ISSUE THREAD

**Issue by blackears** [musescore/MuseScore#14404]
**Describe the bug**
Tools/Explode crashes if you try to use it on measures that have chords with mismatching numbers of notes.

**To Reproduce**
Create a new score.
Add three staves to the score.
In measure 1 of the top staff, enter one chord with 3 notes and a second chord with 2 notes.
select the measure and extend your selection to include the two staves below it.
Choose Tools/Explode from the menu.
Musescore will crash.

**Expected behavior**
Musescore should be able to handle this situation gracefully and not crash.  It would be helpful if it could do its best to explode this measure, even though it has invalid data.  Eg, it could just enter a rest where the missing note is.

**Platform information**
Wundows 10

**Comment by lyrra** [comment]
Reproduced on linux, seems to be an assertion fail that forces the crash.
<details><summary>backtrace:</summary>

```
#2  0x00007ffff566240f in __assert_fail_base (fmt=0x7ffff57da6a8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555557e077f2 "!_notes.empty()",
    file=0x555557e077c0 "src/engraving/libmscore/chord.cpp", line=980, function=<optimized out>) at assert.c:92
#3  0x00007ffff5671662 in __GI___assert_fail (assertion=0x555557e077f2 "!_notes.empty()", file=0x555557e077c0 "src/engraving/libmscore/chord.cpp", line=980,
    function=0x555557e07c18 "virtual void mu::engraving::Chord::computeUp()") at assert.c:101
#4  0x0000555555d09b40 in mu::engraving::Chord::computeUp (this=0x555561d829c0) at src/engraving/libmscore/chord.cpp:980
#5  0x0000555555c71398 in mu::engraving::LayoutMeasure::getNextMeasure (options=..., ctx=...) at src/engraving/layout/layoutmeasure.cpp:713
#6  0x0000555555c83f1f in mu::engraving::LayoutSystem::collectSystem (options=..., ctx=..., score=0x55555d9bfa20) at src/engraving/layout/layoutsystem.cpp:195
#7  0x0000555555c68ba8 in mu::engraving::Layout::doLayoutRange (this=0x55555d9cad68, options=..., st=..., et=...) at src/engraving/layout/layout.cpp:217
#8  0x0000555555a1a03e in mu::engraving::Score::doLayoutRange (this=0x55555d9bfa20, st=..., et=...) at src/engraving/libmscore/score.cpp:5495
#9  0x0000555555d5289b in mu::engraving::Score::update (this=0x55555d9bfa20, resetCmdState=false, layoutAllParts=false) at src/engraving/libmscore/cmd.cpp:429
#10 0x0000555555d51d98 in mu::engraving::Score::endCmd (this=0x55555d9bfa20, rollback=false, layoutAllParts=false) at src/engraving/libmscore/cmd.cpp:360
#11 0x000055555627ef61 in mu::notation::NotationUndoStack::commitChanges (this=0x5555596f99d0) at src/notation/internal/notationundostack.cpp:131
#12 0x00005555564f9561 in mu::notation::NotationInteraction::apply (this=0x555559d71540) at src/notation/internal/notationinteraction.cpp:205
#13 0x0000555556510427 in mu::notation::NotationInteraction::explodeSelectedStaff (this=0x555559d71540) at src/notation/internal/notationinteraction.cpp:4043
```
</details>
