### ISSUE TITLE
[MU4 Issue] Crash when dragging glissando line

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#14426]
**To Reproduce**
1. Click and drag gliss grip
2. Click and drag gliss text

https://user-images.githubusercontent.com/90187801/200642774-ed01b96b-bbbd-42a9-8aac-ac126c46cec5.mp4

**Platform information**
macOS, Windows, Linux

**Comment by lyrra** [comment]
Reproduced on linux.
<details><summary> backtrace + patch </summary>

```
#0  0x0000555555a8f6d4 in mu::engraving::ElementEditData::pushProperty (this=0x0, pid=mu::engraving::Pid::OFFSET2) at src/engraving/libmscore/engravingitem.h:606
#1  0x0000555555e766a2 in mu::engraving::LineSegment::startDrag (this=0x55556066e960, ed=...) at src/engraving/libmscore/line.cpp:221
#2  0x0000555555db7f4e in mu::engraving::SingleElementGroup::startDrag (this=0x55555e545b30, ed=...) at src/engraving/libmscore/elementgroup.cpp:29
#3  0x00005555564fdf1b in mu::notation::NotationInteraction::startDrag(std::vector<mu::engraving::EngravingItem*, std::allocator<mu::engraving::EngravingItem*> > const&, mu::PointX<double> const&, std::function<bool (mu::engraving::EngravingItem const*)> const&) (this=0x55555c0bd8a0, elems=std::vector of length 1, capacity 1 = {...}, eoffset=..., isDraggable=...)
    at src/notation/internal/notationinteraction.cpp:904
#4  0x00005555564a6cba in mu::notation::NotationViewInputController::startDragElements (this=0x55555cba97c0, elementsType=mu::engraving::ElementType::GLISSANDO_SEGMENT, elementsOffset=...)
    at src/notation/view/notationviewinputcontroller.cpp:742


class ElementEditData
{
...
    void pushProperty(Pid pid)
    {
        propertyData.push_back(PropertyData({ pid, e->getProperty(pid), e->propertyFlags(pid) })); <--- LINE 606
    }
...
}

----------------------------------------------

Possible fix (doesn't crash, can still drag by text (not possible in MU3)):

diff --git a/src/engraving/libmscore/line.cpp b/src/engraving/libmscore/line.cpp
index 2aa8631d1e..245be20c1b 100644
--- a/src/engraving/libmscore/line.cpp
+++ b/src/engraving/libmscore/line.cpp
@@ -218,7 +218,9 @@ void LineSegment::startDrag(EditData& ed)
 {
     SpannerSegment::startDrag(ed);
     ElementEditDataPtr eed = ed.getData(this);
-    eed->pushProperty(Pid::OFFSET2);
+    if (eed) {
+        eed->pushProperty(Pid::OFFSET2);
+    }
 }
 
 //---------------------------------------------------------

```
</details>

**Comment by DmitryArefiev** [comment]
Fixed in #14433

**Comment by Jojo-Schmitz** [comment]
Reported a long time ago in https://musescore.org/en/node/328488 (and for 3.6.2)

**Comment by DmitryArefiev** [comment]
That crash was not so noticeable in 3.6.2 as in 4.0, so it just has gone unnoticed.. unfortunately

**Comment by Jojo-Schmitz** [comment]
Pity is that the fix went unnoticed for too long too

**Comment by DmitryArefiev** [comment]
Agree!
