### ISSUE TITLE
[MU4 Issue] muse-hub-service crashes and relaunches every few seconds

### ISSUE THREAD

**Issue by mrbumpy409** [musescore/MuseScore#15189]
**Describe the bug**
I've been trying to find out why muse-hub fails to launch on my system (KDE neon--details below). Watching the task manager, I see the "Muse.Service" and "muse-hub-servic" processes starting and then quickly crashing, then starting again, etc. forever.

Each time this happens, the following gets printed to the Linux system log:

```
12/14/22 11:13 PM	systemd	Started Muse Hub Helper Service.
12/14/22 11:13 PM	muse-hub-service	Unhandled exception. System.IO.IOException: Invalid argument : '/proc/2622/task/2622/net'
12/14/22 11:13 PM	muse-hub-service	   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.StartRaisingEvents()
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
12/14/22 11:13 PM	muse-hub-service	   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
12/14/22 11:13 PM	muse-hub-service	   at Microsoft.Extensions.Hosting.HostBuilder.Build()
12/14/22 11:13 PM	muse-hub-service	   at Program.<Main>$(String[] args) in /home/runner/work/Muse/Muse/Windows/src/Muse.Service/Program.cs:line 19
12/14/22 11:13 PM	muse-hub-service	   at Program.<Main>(String[] args)
12/14/22 11:13 PM	muse-hub-service	Aborted
12/14/22 11:13 PM	systemd	muse-hub.service: Main process exited, code=exited, status=134/n/a
12/14/22 11:13 PM	systemd	muse-hub.service: Failed with result 'exit-code'.
12/14/22 11:13 PM	systemd	muse-hub.service: Consumed 3.049s CPU time.
12/14/22 11:13 PM	systemd	muse-hub.service: Scheduled restart job, restart counter is at 14.
12/14/22 11:13 PM	systemd	Stopped Muse Hub Helper Service.
12/14/22 11:13 PM	systemd	muse-hub.service: Consumed 3.049s CPU time.
```
**The Affected System (Desktop PC)**
OS: KDE neon User Edition (based on Ubuntu 22.04)
Muse Hub version: 1.0.0.392 (deb package)
CPU: Intel Core i7-990x Gulftown (3.46 GHz hexa-core, Socket 1366) @ 4.15 GHz
RAM: 24GB (6x G.Skill 4GB DDR3 PC3-10666 1333 MHz) @ 1430 MHz

I don't believe the issue is KDE neon, as I have been able to get Muse Hub to work on two other setups using this same operating system with all software up to date. One working setup is my laptop, and the other is a Virtualbox install running on the desktop PC listed above. Despite eventually getting Muse Hub to run on those two systems, it would not launch the first time I tried. In each case, I alternated launching Muse Hub from the application shortcut and the terminal until it finally started up after a few tries.

**Comment by DominicMaas** [comment]
Looks like some weird .NET error, I'm not using the configuration system, so I'll see if I can disable it so this error won't appear for you.

**Comment by mrbumpy409** [comment]
Thanks, Dominic! Is this something I just need to wait for an update on, or is there upstream code I can test somewhere?
