### ISSUE TITLE
[MU4 Issue] Entering Roman numeral analysis crashes when using screen reader

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#15897]
**Describe the bug**
Enter RNA text crashes MuseScore if a sxcreen reader isrunning

**To Reproduce**
1. New score (be sure to have a screen reader running)
2. Select first rest
3. Add / Text / Roman numeral analysis
4. Type I
5. Press Esc
6. See error: crash

**Expected behavior**
The text is entered normally

**Screenshots**

**Platform information**
Confirmed using NVDA, JAWS, and Narrator on Windows, also Orca on Linux.  In some cases apparently the crash might happen sooner, like right after step 3, depending on how quickly you type I guess.

See https://musescore.org/en/node/342415 for more info

**Comment by NoahCarverMusic** [comment]
> In some cases apparently the crash might happen sooner, like right after step 3, depending on how quickly you type I guess.
> 
> See https://musescore.org/en/node/342415 for more info

Hi. Some clarification to your comment above. For me, the crash occurs immediately after invoking the "Roman numeral analysis" menu item. No roman numeral entry is necessary to cause the crash in my case.

**Comment by MarcSabatella** [comment]
Using orca, the following gets printed to the console in the window I started orca from (not the window I started MuseScore from):

(orca:7559): dbind-CRITICAL **: 13:17:59.426: atspi_accessible_set_cache_mask: assertion 'accessible->parent.app != NULL' failed

Which is probably a good clue.

**Comment by Eism** [comment]
@MarcSabatella 
I tested it on Linux with Orca. 
The crash occurs on this line [harmony.cpp#L2124](https://github.com/musescore/MuseScore/blob/master/src/engraving/libmscore/harmony.cpp#L2124) with 
```
terminate called after throwing an instance of 'std::regex_error'
  what():  Invalid special open parenthesis.
```

You implemented it in this PR https://github.com/musescore/MuseScore/pull/5459

The regex looks invalid and the crash started to occur after replacing QRegularExpression with std::regex. 

Can you please explain how regex was supposed to work?
And
Do we really need regex here, or can we just use a replacement like for rnaReplacements?

**Comment by MarcSabatella** [comment]
BTW, a brute force non-regex solution might be, first just replace all the b's with flat (♭) normally, but then do a second pass and replace occurrences of "\♭" with the letter b again.

**Comment by NoahCarverMusic** [comment]
Here's a debug log from NVDA detailing what occurs from NVDA's perspective. This snippet begins immediately after I press enter on the "Roman numeral analysis" menu item. The full log is also attached.

```
DEBUG - editableText.EditableText._hasCaretMoved (01:59:30.928) - MainThread (4040):
Focus event. Elapsed: 20 ms
DEBUGWARNING - NVDAObjects.behaviors.EditableText._reportErrorInPreviousWord (01:59:30.938) - MainThread (4040):
Error fetching last character of previous word
Traceback (most recent call last):
  File "NVDAObjects\UIA\__init__.pyc", line 427, in __init__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "NVDAObjects\behaviors.pyc", line 191, in _reportErrorInPreviousWord
  File "documentBase.pyc", line 74, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 429, in __init__
RuntimeError: No selection available
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (01:59:30.940) - MainThread (4040):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30155, 30138, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
DEBUGWARNING - eventHandler.executeEvent (01:59:30.941) - MainThread (4040):
error executing event: typedCharacter on <NVDAObjects.Dynamic_MenuItemEditableTextWithAutoSelectDetectionUIA object at 0x0819B830> with extra args of {'ch': '\r'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\behaviors.pyc", line 236, in event_typedCharacter
  File "NVDAObjects\__init__.pyc", line 1143, in event_typedCharacter
  File "speech\speech.pyc", line 1106, in speakTypedCharacters
  File "api.pyc", line 337, in isTypingProtected
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 1027, in _get_isProtected
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1619, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 985, in _getUIACacheablePropertyValue
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
DEBUGWARNING - eventHandler.executeEvent (01:59:31.130) - MainThread (4040):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x081AB6D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "C:\Users\noahc\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 465, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 110, in next
  File "C:\Users\noahc\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 243, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\behaviors.pyc", line 247, in event_gainFocus
  File "NVDAObjects\UIA\__init__.pyc", line 1316, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1198, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1095, in reportFocus
  File "speech\speech.pyc", line 609, in speakObject
  File "speech\speech.pyc", line 649, in getObjectSpeech
  File "speech\speech.pyc", line 501, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1581, in _get_keyboardShortcut
  File "NVDAObjects\UIA\__init__.pyc", line 985, in _getUIACacheablePropertyValue
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
```
[RNA Crash NVDA Debug.log](https://github.com/musescore/MuseScore/files/10471714/RNA.Crash.NVDA.Debug.log)

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 12.6
