### ISSUE TITLE
[Muse Hub] Returns segfault on launch

### ISSUE THREAD

**Issue by Smartich0ke** [musescore/MuseScore#17436]
### Issue type

Crash or freeze

### Bug description

Running on a pretty much fresh install of ubuntu 23.10 with GNOME 44 on X11.
I installed Muse Hub as a deb.
When I try to open it (either through command-line or desktop launcher), a window briefly opens up and closes again after a few seconds and returns a segfault. 

### Steps to reproduce

1. Go to musescore.org
2. Download the Muse Hub deb
3. Install it (I used `dpkg -i`)
4. Launch it
5. Watch it fail

### Screenshots/Screen recordings

[Screencast from 2023-05-02 17-28-12.webm](https://user-images.githubusercontent.com/41409702/235611589-10dfe474-ec82-4945-a168-451cb1f14154.webm)

### MuseScore Version

1.0.1.451

### Regression

No.

### Operating system

Ubuntu 23.10

### Additional context

Crash log:
```
2023-05-02 17:15:38.5140|INFO|Muse.Client.Linux.App|Attempting to set the users language to en-US using file /opt/muse-hub/Assets/Strings/en-US/Localizable.strings
2023-05-02 17:15:39.1112|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.1112|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.1112|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.1237|INFO|Muse.Client.Common.Services.MuseBackgroundService|Attempting to connect to background service (starting background thread)...
2023-05-02 17:15:39.1257|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.1257|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.1257|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.1335|INFO|Muse.Client.Common.Services.MuseBackgroundService|Connected to the muse service
2023-05-02 17:15:39.2571|INFO|Muse.Client.Common.Services.MuseBackgroundService|Received message from background service - Type: Muse.Common.Messages.Actions.UpdateAppStateAction, Data: -
2023-05-02 17:15:39.2571|DEBUG|Muse.Common.Services.MuseHubStateManager|Syncing State...
2023-05-02 17:15:39.3539|INFO|Muse.Client.Common.Services.UpdateManager|Checking for updates...
2023-05-02 17:15:39.3569|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.3569|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.3618|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.3618|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.3677|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:39.3677|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:40.2590|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 1131.7133ms - 200
2023-05-02 17:15:40.2620|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 1155.5586ms - 200
2023-05-02 17:15:40.2959|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|Start processing HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:40.2959|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Sending HTTP request POST https://muse-webservice.azurewebsites.net/graphql
2023-05-02 17:15:40.3451|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 1219.1666ms - 200
2023-05-02 17:15:40.3451|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 1238.9873ms - 200
2023-05-02 17:15:40.3573|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 1231.3813ms - 200
2023-05-02 17:15:40.3573|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 1251.1484ms - 200
2023-05-02 17:15:40.4033|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 1046.2323ms - 200
2023-05-02 17:15:40.4033|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 1046.4483ms - 200
2023-05-02 17:15:40.4679|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 1106.0115ms - 200
2023-05-02 17:15:40.4679|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 1106.2184ms - 200
2023-05-02 17:15:40.5279|INFO|System.Net.Http.HttpClient.CosmosApi.ClientHandler|Received HTTP response headers after 1160.0851ms - 200
2023-05-02 17:15:40.5279|INFO|System.Net.Http.HttpClient.CosmosApi.LogicalHandler|End processing HTTP request after 1160.2654ms - 200
2023-05-02 17:15:40.5374|INFO|Muse.Client.Common.Services.MuseBackgroundService|Sending message to background service - Type: Muse.Common.Messages.Actions.RegisterHiddenDownloadAction, Data: ItemId=musesampler;ItemType=Application;P2PInfoFile=https://muse-webservice.azurewebsites.net/musedownload/application-builds/8c14fcf0-f06a-40a7-a530-227eb382c84a;Version=0.3.2.18;ItemName=MuseSampler
2023-05-02 17:15:40.5480|INFO|Muse.Client.Common.Services.MuseBackgroundService|Sending message to background service - Type: Muse.Common.Messages.Actions.RegisterHiddenDownloadAction, Data: ItemId=hub;ItemType=Application;P2PInfoFile=https://muse-webservice.azurewebsites.net/musedownload/application-builds/b4d48eeb-e3e1-4fe9-97d1-ce9eed3f5fe0;Version=1.0.1.451;ItemName=Muse Hub
2023-05-02 17:15:40.6979|FATAL|Muse.Client.Linux.App|Application has encountered a fatal exception!|System.IO.IOException: No space left on device : '/tmp/muse-hub/cache/images'
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Muse.Client.Common.Services.ImageManager..ctor(ILogger`1 logger, IHttpClientFactory httpClientFactory) in /home/runner/work/Muse/Muse/WindowsLinuxCommon/src/Muse.Client.Common/Services/ImageManager.cs:line 62
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Muse.Client.Linux.Controls.MuseImage.LoadImageAsync(ImageSet imageSet) in /home/runner/work/Muse/Muse/Linux/src/Muse.Client.Linux/Controls/MuseImage.cs:line 85
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at Muse.Client.Linux.Program.Main(String[] args) in /home/runner/work/Muse/Muse/Linux/src/Muse.Client.Linux/Program.cs:line 21
Segmentation fault (core dumped)

```

**Comment by Eism** [comment]
Hi! Unfortunately, we cannot handle Muse Hub issues here in the MuseScore repository. Please report it to the Muse Hub team directly, at https://musehub.zendesk.com/. Thanks!

PS: 
> No space left on device: '/tmp/muse-hub/cache/images'

This error indicates that there is not enough space on the device. Freeing up space may help you.
However, it is a problem and it is better to contact MuseHub team at the link above.
