### ISSUE TITLE
Crash on quit (Linux with enabled global menu bar)

### ISSUE THREAD

**Issue by adazem009** [musescore/MuseScore#18572]
### Issue type

Crash or freeze

### Bug description

MuseScore 4.1 crashes on quit when the platform menu bar on Linux is enabled.

### Steps to reproduce

1. Enable global menu bar in your desktop environment.
2. Open MuseScore.
3. Close MuseScore.

### MuseScore Version

4.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Kubuntu 22.04 (KDE Plasma 5.24.7)

### Additional context

```
#0  0x00007ffff5b5afb4 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff5d785ec in QObjectPrivate::connectImpl(QObject const*, int, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff5d78b15 in QObject::connectImpl(QObject const*, void**, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007fff7eb6bbfc in  ()
    at /usr/lib/x86_64-linux-gnu/qt5/qml/Qt/labs/platform/libqtlabsplatformplugin.so
#4  0x00007fff7eb6d1c0 in  ()
    at /usr/lib/x86_64-linux-gnu/qt5/qml/Qt/labs/platform/libqtlabsplatformplugin.so
#5  0x00007fff7eb6d23d in  ()
    at /usr/lib/x86_64-linux-gnu/qt5/qml/Qt/labs/platform/libqtlabsplatformplugin.so
#6  0x00007fff7eb5f457 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/Qt/labs/platform/libqtlabsplatformplugin.so
#7  0x00007ffff5d74a6e in QObjectPrivate::deleteChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff5d7f924 in QObject::~QObject() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fff7eb5f4c7 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/Qt/labs/platform/libqtlabsplatformplugin.so
#10 0x00007ffff5d74a6e in QObjectPrivate::deleteChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff5d7f924 in QObject::~QObject() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff7c63859 in  () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#13 0x00007ffff5d74a6e in QObjectPrivate::deleteChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff5d7f924 in QObject::~QObject() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff7c64789 in  () at /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#16 0x00007ffff5d74a6e in QObjectPrivate::deleteChildren() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff5d7f924 in QObject::~QObject() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fff8d713381 in  () at /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.so
#19 0x00007ffff76e29ce in QQmlApplicationEnginePrivate::cleanUp() () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#20 0x00007ffff76e2a1d in QQmlApplicationEngine::~QQmlApplicationEngine() () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#21 0x00007ffff76e2a3d in QQmlApplicationEngine::~QQmlApplicationEngine() () at /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#22 0x0000555556b8f9c7 in mu::ui::UiEngine::quit() (this=0x5555596eecc0 <mu::ui::UiEngine::instance()::e>) at /home/adazem009/tmp/MuseScore/src/framework/ui/internal/uiengine.cpp:66
#23 0x0000555555784965 in mu::app::App::run(int, char**) (this=0x7fffffffd820, argc=1, argv=0x7fffffffdd38) at /home/adazem009/tmp/MuseScore/src/app/app.cpp:353
#24 0x000055555576c1ae in main(int, char**) (argc=1, argv=0x7fffffffdd38) at /home/adazem009/tmp/MuseScore/src/app/main.cpp:341
```
Might be related to #16456 because Linux uses the same platform menu bar implementation as macOS.

**Comment by adazem009** [comment]
I think I've found a fix. Can somebody assign me?

**Comment by adazem009** [comment]
I should add that it's easiest to reproduce this in KDE Plasma (in my case it's 5.24.7).
MuseScore crashes every time I quit.

**Comment by adazem009** [comment]
I've also tested the linked PR on the VM and it doesn't crash anymore.

**Comment by DmitryArefiev** [comment]
@adazem009 Did that happen in 4.0.2?

**Comment by adazem009** [comment]
> @adazem009 Did that happen in 4.0.2?

No, because 4.0.2 didn't have any platform menu bar support on Linux. It only happens when the global menu bar is enabled.
