### ISSUE TITLE
MuseScore 4.1.1 hangs on Fedora 38

### ISSUE THREAD

**Issue by ycollet** [musescore/MuseScore#18911]
### Issue type

Crash or freeze

### Bug description

I compiled MuseScore 4.1.1 on Fedora 38 and it hangs at startup.
The messages I can read in the console just before the crash:
```
19:16:21.016 | WARN  | main_thread | AbstractCloudService | readTokens: Could not find the tokens file: /home/collette/.local/share/MuseScore/MuseScore4/musescorecom_cred.dat
19:16:21.016 | WARN  | main_thread | AbstractCloudService | readTokens: Could not find the tokens file: /home/collette/.local/share/MuseScore/MuseScore4/audiocom_cred.dat
Erreur de segmentation (core dumped)
```

### Steps to reproduce

Compile musescore with these cmake options:
       -DMUE_BUILD_UNIT_TESTS:BOOL=OFF \
       -DMUE_BUILD_CRASHPAD_CLIENT:BOOL=ON \
       -DMUE_BUILD_VST_MODULE:BOOL=ON \
       -DMUE_BUILD_VIDEOEXPORT_MODULE:BOOL=OFF \
       -DMUE_BUILD_UPDATE_MODULE:BOOL=OFF \
       -DMUSESCORE_BUILD_MODE=release \
       -DMUSESCORE_BUILD_NUMBER=1 \
       -DMUSESCORE_REVISION=%{revision} \
       -DVST3_SDK_PATH:PATH=$CURRENT_PATH/vst3sdk \
       -DCMAKE_SKIP_RPATH:BOOL=ON \
       -DX86_MAY_HAVE_SSE:BOOL=ON \
       -DX86_MAY_HAVE_SSE2:BOOL=ON \
       -DX86_MAY_HAVE_SSE4_1:BOOL=OFF \
       -DX86_MAY_HAVE_AVX:BOOL=OFF \
       -DOPUS_X86_PRESUME_SSE:BOOL=ON \
       -DOPUS_X86_PRESUME_SSE2:BOOL=ON
and start mscore.

### MuseScore Version

4.1.1

### Regression

I don't know

### Operating system

Fedora 38

**Comment by ycollet** [comment]
The content of the log file:
```
2023-08-03T21:25:29.835 | INFO  | main_thread | GlobalModule | onPreInit: log path: /home/collette/.local/share/MuseScore/MuseScore4/logs/MuseScore_230803_212529.log
2023-08-03T21:25:29.836 | INFO  | main_thread | GlobalModule | onPreInit: === Started MuseScore 4.1.1, build number  ===
2023-08-03T21:25:29.837 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
2023-08-03T21:25:29.837 | WARN  | main_thread | IpcSocket  | connect: failed connect to server
2023-08-03T21:25:29.837 | INFO  | main_thread | IpcSocket  | connect: success connected to ipc server
2023-08-03T21:25:29.837 | INFO  | 140736347502272 | IpcServer  | listen: id: "5c2e80442997421b98be1002d57fbc29"
2023-08-03T21:25:30.471 | DEBUG | main_thread | DiagnosticsModule | onInit: crash server url:
2023-08-03T21:25:30.471 | ERROR | main_thread | CrashHandler | start: crash handler not exists, path: /usr/bin/crashpad_handler
2023-08-03T21:25:30.471 | ERROR | main_thread | DiagnosticsModule | onInit: failed start crash handler
~   
```

MuseScore has been installed without the crash_handler binary. I will try to install it manually but fedora doesn't accept "non fedora binary" like crash_handler  ...

**Comment by ycollet** [comment]
crash_handler is missing a non existent shared library:
```
/usr/bin/crashpad_handler: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

```

**Comment by ycollet** [comment]
Interesting fact ... I was trying to get a stack track and .... gdb hangs :)

**Comment by ycollet** [comment]
If I don't load the symbols and with -DMUE_BUILD_CRASHPAD_CLIENT:BOOL=OFF; I can get a stack trace ... But If I load the debug symbols, gdb hangs.
```
#0  0x00007ffff50c98ad in __memmove_sse2_unaligned_erms () at /lib64/libc.so.6
#1  0x00007ffff581115b in QResourceFileEngine::read(char*, long long) () at /lib64/libQt5Core.so.5
#2  0x00007ffff57f9bc4 in QFileDevice::readData(char*, long long) () at /lib64/libQt5Core.so.5
#3  0x00007ffff5801275 in QIODevicePrivate::read(char*, long long, bool) () at /lib64/libQt5Core.so.5
#4  0x00007ffff5801cf5 in QIODevice::readAll() () at /lib64/libQt5Core.so.5
#5  0x00007ffff5e33573 in QFontDatabase::addApplicationFont(QString const&) () at /lib64/libQt5Gui.so.5
#6  0x0000555555da3ef5 in mu::draw::QFontProvider::addSymbolFont(mu::String const&, mu::io::path_t const&) ()
#7  0x00005555561553a7 in mu::engraving::EngravingFont::ensureLoad() ()
#8  0x0000555555e13974 in mu::engraving::EngravingModule::onInit(mu::framework::IApplication::RunMode const&) ()
#9  0x0000555555a1753c in main ()
```

**Comment by ycollet** [comment]
And finally a better stack trace:
```
#0  0x00007ffff50c98ad in __memmove_sse2_unaligned_erms () at /lib64/libc.so.6
#1  0x00007ffff581115b in QResourceFileEngine::read(char*, long long) () at /lib64/libQt5Core.so.5
#2  0x00007ffff57f9bc4 in QFileDevice::readData(char*, long long) () at /lib64/libQt5Core.so.5
#3  0x00007ffff5801275 in QIODevicePrivate::read(char*, long long, bool) () at /lib64/libQt5Core.so.5
#4  0x00007ffff5801cf5 in QIODevice::readAll() () at /lib64/libQt5Core.so.5
#5  0x00007ffff5e33573 in QFontDatabase::addApplicationFont(QString const&) () at /lib64/libQt5Gui.so.5
#6  0x0000555555da3ef5 in mu::draw::QFontProvider::addSymbolFont(mu::String const&, mu::io::path_t const&) (this=this@entry=0x5555587cb130, family=..., path=...)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/framework/draw/internal/qfontprovider.cpp:60
#7  0x00005555561553a7 in mu::engraving::EngravingFont::ensureLoad() (this=0x5555586c31b0)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/engraving/internal/engravingfont.cpp:97
#8  0x0000555555e13974 in mu::engraving::EngravingFontsProvider::loadAllFonts() (this=<optimized out>)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/engraving/internal/engravingfontsprovider.cpp:103
#9  mu::engraving::EngravingModule::onInit(mu::framework::IApplication::RunMode const&) (this=0x555558666e20, mode=<optimized out>)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/engraving/engravingmodule.cpp:123
#10 0x0000555555a1753c in mu::app::App::run(int, char**) (argv=<optimized out>, argc=<optimized out>, this=0x7fffffffd410)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/app/app.cpp:193
#11 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/app/main.cpp:341
(gdb) 
#0  0x00007ffff50c98ad in __memmove_sse2_unaligned_erms () at /lib64/libc.so.6
#1  0x00007ffff581115b in QResourceFileEngine::read(char*, long long) () at /lib64/libQt5Core.so.5
#2  0x00007ffff57f9bc4 in QFileDevice::readData(char*, long long) () at /lib64/libQt5Core.so.5
#3  0x00007ffff5801275 in QIODevicePrivate::read(char*, long long, bool) () at /lib64/libQt5Core.so.5
#4  0x00007ffff5801cf5 in QIODevice::readAll() () at /lib64/libQt5Core.so.5
#5  0x00007ffff5e33573 in QFontDatabase::addApplicationFont(QString const&) () at /lib64/libQt5Gui.so.5
#6  0x0000555555da3ef5 in mu::draw::QFontProvider::addSymbolFont(mu::String const&, mu::io::path_t const&) (this=this@entry=0x5555587cb130, family=..., path=...)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/framework/draw/internal/qfontprovider.cpp:60
#7  0x00005555561553a7 in mu::engraving::EngravingFont::ensureLoad() (this=0x5555586c31b0)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/engraving/internal/engravingfont.cpp:97
#8  0x0000555555e13974 in mu::engraving::EngravingFontsProvider::loadAllFonts() (this=<optimized out>)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/engraving/internal/engravingfontsprovider.cpp:103
#9  mu::engraving::EngravingModule::onInit(mu::framework::IApplication::RunMode const&) (this=0x555558666e20, mode=<optimized out>)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/engraving/engravingmodule.cpp:123
#10 0x0000555555a1753c in mu::app::App::run(int, char**) (argv=<optimized out>, argc=<optimized out>, this=0x7fffffffd410)
    at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/app/app.cpp:193
#11 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/mscore-mao-4.1.1-2.fc38.x86_64/src/app/main.cpp:341
```

**Comment by ycollet** [comment]
Probably a problem due to an incorrect installation of fonts. I am currently trying to fix that.

**Comment by Eism** [comment]
maybe related to #18795

**Comment by ycollet** [comment]
I removed the fedora specific compilations flags and now Musescore-4.0.2 is running fine.
I will do the same test with 4.1.1 soon.
Here are the fedora specfic compilation flags:
```
#  CFLAGS="${CFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer }" ; export CFLAGS ; 
#  CXXFLAGS="${CXXFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer }" ; export CXXFLAGS ; 
#  LDFLAGS="${LDFLAGS:--Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1  }" ; export LDFLAGS ; 
```

**Comment by ycollet** [comment]
Tested with 4.1.1 and it works too. Next step: trying to identify the specific flag triggering the bug.
Apparently, it's a double free problem but I am not able to locate the problem yet, gdb hangs with mscore ...

**Comment by ycollet** [comment]
Disabling LTO fixed the problem.

**Comment by Jojo-Schmitz** [comment]
What is LTO?

**Comment by ycollet** [comment]
Link Time Optimization. All the flags related to -flto on gcc.
Some optimizations performed during link time.
I think LTO has been introduced in gcc 9 and has improved a lot but from time to time, a project fails to build with LTO.

**Comment by Jojo-Schmitz** [comment]
Thanks
