### ISSUE TITLE
Intermitten crash on score opening at `mu::engraving::PropertyValue::get<muse::String>`

### ISSUE THREAD

**Issue by bluebear94** [musescore/MuseScore#22397]
### Issue type

Crash or freeze

### Bug description

When opening a score, MuseScore sometimes crashes.

This seems to be caused by a different bug from #22396.

### Steps to reproduce

1. Open MuseScore
2. Open a score

### MuseScore Version

OS: EndeavourOS, Arch.: x86_64, MuseScore version (64-bit): 4.4.0-, revision: github-musescore-musescore- (ca6e8a8)

### Regression

I don't know

### Operating system

Linux

### Additional context

GDB backtrace when opening a score:

```
#0  0x00007ffff4caeb39 in __cxxabiv1::__dynamic_cast
    (src_ptr=0x555500000000, src_type=0x555558d5ada8 <typeinfo for mu::engraving::PropertyValue::IArg>, dst_type=0x555558d5d470 <typeinfo for mu::engraving::PropertyValue::Arg<muse::String>>, src2dst=0) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/dyncast.cc:53
#1  0x0000555556131ad6 in mu::engraving::PropertyValue::get<muse::String> (this=0x59767100)
    at /home/felirovas/conlang/MuseScore/src/engraving/dom/../style/../types/propertyvalue.h:457
#2  mu::engraving::PropertyValue::value<muse::String> (this=this@entry=0x7fffffff96f0)
    at /home/felirovas/conlang/MuseScore/src/engraving/dom/../style/../types/propertyvalue.h:297
#3  0x00005555562d02cd in mu::engraving::TextLineBase::setProperty (this=0x55555c6b3850, id=<optimized out>, v=...)
    at /home/felirovas/conlang/MuseScore/src/engraving/dom/textlinebase.cpp:338
#4  0x00005555560f015b in mu::engraving::EngravingObject::initElementStyle (this=this@entry=0x55555c6b3850, ss=ss@entry=0x555558e45d20 <mu::engraving::pedalStyle>)
    at /home/felirovas/conlang/MuseScore/src/engraving/dom/engravingobject.cpp:353
#5  0x00005555561ea19d in mu::engraving::Pedal::Pedal (this=this@entry=0x55555c6b3850, parent=parent@entry=0x55555c7eb770)
    at /home/felirovas/conlang/MuseScore/src/engraving/dom/pedal.cpp:110
#6  0x000055555610030c in mu::engraving::Factory::doCreateItem (type=<optimized out>, parent=0x55555c7eb770)
    at /home/felirovas/conlang/MuseScore/src/engraving/dom/factory.cpp:151
#7  0x0000555556102b3d in mu::engraving::Factory::createItem (type=<optimized out>, parent=<optimized out>, isAccessibleEnabled=isAccessibleEnabled@entry=true)
    at /home/felirovas/conlang/MuseScore/src/engraving/dom/factory.cpp:125
#8  0x0000555556102c7a in mu::engraving::Factory::createItemByName (name=..., parent=<optimized out>, isAccessibleEnabled=isAccessibleEnabled@entry=true)
    at /home/felirovas/conlang/MuseScore/src/engraving/dom/factory.cpp:304
#9  0x00005555563e5af4 in mu::engraving::read410::ConnectorInfoReader::read (this=0x55555c73b690)
    at /home/felirovas/conlang/MuseScore/src/engraving/rw/read410/connectorinforeader.cpp:98
#10 0x00005555563e5b79 in mu::engraving::read410::ConnectorInfoReader::readConnector
    (info=std::shared_ptr<mu::engraving::read410::ConnectorInfoReader> (use count 2, weak count 0) = {...}, e=..., ctx=...)
    at /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1665
#11 0x00005555563c81cf in mu::engraving::read410::TRead::readSpanner (e=..., ctx=..., current=<optimized out>, track=4)
    at /home/felirovas/conlang/MuseScore/src/engraving/rw/read410/tread.cpp:4687
#12 0x00005555563bce81 in mu::engraving::read410::MeasureRead::readVoice (measure=0x55555c815c50, e=..., ctx=..., staffIdx=1, irregular=false)
    at /home/felirovas/conlang/MuseScore/src/engraving/rw/read410/measureread.cpp:342
#13 0x00005555563beffe in mu::engraving::read410::MeasureRead::readMeasure (measure=measure@entry=0x55555c815c50, e=..., ctx=..., staffIdx=staffIdx@entry=1)
    at /home/felirovas/conlang/MuseScore/src/engraving/rw/read410/measureread.cpp:113
#14 0x00005555563ba070 in mu::engraving::read410::StaffRead::readStaff (score=score@entry=0x55555b201790, e=..., ctx=...)
    at /home/felirovas/conlang/MuseScore/src/engraving/rw/read410/staffread.cpp:108
#15 0x00005555563b1ad8 in mu::engraving::read410::Read410::readScore410 (score=score@entry=0x55555b201790, e=..., ctx=...)
    at /home/felirovas/conlang/MuseScore/src/engraving/rw/read410/read410.cpp:124
#16 0x00005555563b2d0f in mu::engraving::read410::Read410::readScore (this=<optimized out>, score=0x55555b201790, e=..., data=0x7fffffffb320)
    at /home/felirovas/conlang/MuseScore/src/engraving/rw/read410/read410.cpp:89
#17 0x000055555631ce96 in mu::engraving::MscLoader::readMasterScore
    (this=this@entry=0x7fffffffb818, score=score@entry=0x55555b201790, e=..., ignoreVersionError=ignoreVersionError@entry=false, out=out@entry=0x7fffffffb320, styleHook=0x7fffffffb2a0) at /home/felirovas/conlang/MuseScore/src/engraving/rw/mscloader.cpp:239
#18 0x000055555631e16e in mu::engraving::MscLoader::loadMscz
    (this=this@entry=0x7fffffffb818, masterScore=0x55555b201790, mscReader=..., settingsCompat=..., ignoreVersionError=ignoreVersionError@entry=false)
    at /home/felirovas/conlang/MuseScore/src/engraving/rw/mscloader.cpp:131
#19 0x00005555573158eb in mu::engraving::EngravingProject::loadMscz (this=0x55555a572ec0, msc=..., settingsCompat=..., ignoreVersionError=ignoreVersionError@entry=false)
    at /home/felirovas/conlang/MuseScore/src/engraving/engravingproject.cpp:149
#20 0x0000555556a21f49 in mu::project::NotationProject::doLoad (this=this@entry=0x55555c88dac0, path=..., stylePath=..., forceMode=forceMode@entry=false, format="mscz")
    at /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1665
#21 0x0000555556a2407f in mu::project::NotationProject::load (this=this@entry=0x55555c88dac0, path=..., stylePath=..., forceMode=forceMode@entry=false, format_="mscz")
    at /home/felirovas/conlang/MuseScore/src/project/internal/notationproject.cpp:124
#22 0x0000555556a254bd in mu::project::ProjectActionsController::loadProject (this=this@entry=0x5555594fdfa0, filePath=...)
    at /home/felirovas/conlang/MuseScore/src/project/internal/projectactionscontroller.cpp:273
#23 0x0000555556a25d25 in mu::project::ProjectActionsController::doOpenProject (this=this@entry=0x5555594fdfa0, filePath=...)
    at /home/felirovas/conlang/MuseScore/src/project/internal/projectactionscontroller.cpp:308
#24 0x0000555556a29b1d in mu::project::ProjectActionsController::openProject (this=this@entry=0x5555594fdfa0, givenPath=..., displayNameOverride=...)
    at /home/felirovas/conlang/MuseScore/src/project/internal/projectactionscontroller.cpp:256
#25 0x0000555556a2aa6e in mu::project::ProjectActionsController::openProject (this=0x5555594fdfa0, file=...)
    at /home/felirovas/conlang/MuseScore/src/project/internal/projectactionscontroller.cpp:190
#26 0x0000555556a00587 in mu::project::ProjectActionsController::openProject (this=0x5555594fdfa0, args=<optimized out>)
    at /home/felirovas/Qt/6.2.4/gcc_64/include/QtCore/qarraydata.h:88
#27 0x0000555556637a22 in std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, muse::actions::ActionData const&)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, muse::actions::ActionData const&) const
    (__args#1=<optimized out>, __args#0=<optimized out>, this=0x55555a800180) at /usr/include/c++/13.2.1/bits/std_function.h:591
#28 muse::actions::ActionsDispatcher::dispatch (this=this@entry=0x5555591feee0, actionCode="file-open", data=...)
    at /home/felirovas/conlang/MuseScore/src/framework/actions/internal/actionsdispatcher.cpp:69
#29 0x0000555556a80a12 in mu::project::ScoresPageModel::openScore (this=<optimized out>, scorePath=<optimized out>, displayNameOverride=...)
    at /home/felirovas/conlang/MuseScore/src/project/view/scorespagemodel.cpp:51
#30 0x0000555556a2f280 in mu::project::ScoresPageModel::qt_metacall (this=0x55555c8ad520, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7fffffffcf38)
    at /home/felirovas/conlang/MuseScore/builds/Linux-Qt6.2.4-gcc_64-Ninja-RelWithDebInfo/src/project/project_autogen/OTUN7GXZT4/moc_scorespagemodel.cpp:197
#31 0x00007ffff6f22f9d in ??? () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Qml.so.6
#32 0x00007ffff6e163aa in ??? () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Qml.so.6
#33 0x00007ffff6e17781 in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Qml.so.6
#34 0x00007ffff6eb855a in ??? () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Qml.so.6
#35 0x00007ffff6eb8988 in ??? () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Qml.so.6
#36 0x00007ffff51a821c in QObject::event(QEvent*) () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Core.so.6
#37 0x00007ffff63769e2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Widgets.so.6
#38 0x00007ffff515a05a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Core.so.6
#39 0x00007ffff515cfbc in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Core.so.6
#40 0x00007ffff53c20c3 in ??? () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Core.so.6
#41 0x00007ffff41cf199 in ??? () at /usr/lib/libglib-2.0.so.0
#42 0x00007ffff422e3bf in ??? () at /usr/lib/libglib-2.0.so.0
#43 0x00007ffff41ce712 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#44 0x00007ffff53c1a4a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Core.so.6
#45 0x00007ffff5165e4b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Core.so.6
#46 0x00007ffff5161f0b in QCoreApplication::exec() () at /home/felirovas/Qt/6.2.4/gcc_64/lib/libQt6Core.so.6
#47 0x0000555555f23425 in mu::app::App::run (this=this@entry=0x7fffffffdf00, argc=<optimized out>, argc@entry=1, argv=argv@entry=0x7fffffffe368)
    at /home/felirovas/conlang/MuseScore/src/app/app.cpp:355
#48 0x0000555555abf151 in main (argc=1, argv=0x7fffffffe368) at /home/felirovas/conlang/MuseScore/src/app/main.cpp:379
```

**Comment by bluebear94** [comment]
Actually, this does seem related to #22396, so I’ll close this issue.
