### ISSUE TITLE
Consistent segfault on startup

### ISSUE THREAD

**Issue by edwloef** [musescore/MuseScore#22926]
### Issue type

Crash or freeze

### Bug description

When installed from the Arch Linux extra repos and started, the program always segfaults before opening a window.

This *could* be the same as #20792, however I don't get the assertion failed line.

### Steps to reproduce

1. run `mscore`

### Screenshots/Screen recordings

![image](https://github.com/musescore/MuseScore/assets/75493688/24ec54b0-3d8f-4b2a-be0c-5a1e985b140d)

### MuseScore Version

4.3.0

### Regression

I don't know

### Operating system

Arch Linux

### Additional context

backtrace: https://pastebin.com/ydG61jLt

**Comment by cbjeukendrup** [comment]
From the backtrace:
```c++
#4  0x00007ffff54d2d60 in std::__glibcxx_assert_fail
    (file=file@entry=0x5555573bfe0c "/usr/include/c++/14.1.1/array", line=line@entry=217, function=function@entry=0x555557342ce0 "constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = mu::engraving::PropertyValue; long unsigned int _Nm = 1437; const_reference = const mu::"..., condition=condition@entry=0x5555573ba9ce "__n < this->size()") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/assert_fail.cc:41
#5  0x0000555556360c10 in std::array<mu::engraving::PropertyValue, 1437ul>::operator[] (this=<optimized out>, __n=18446744073709551601)
    at /usr/include/c++/14.1.1/array:214
        __PRETTY_FUNCTION__ = {<optimized out> <repeats 258 times>}
#6  std::array<mu::engraving::PropertyValue, 1437ul>::operator[] (this=<optimized out>, __n=18446744073709551601) at /usr/include/c++/14.1.1/array:214
        __PRETTY_FUNCTION__ = {<optimized out> <repeats 258 times>}
#7  mu::engraving::MStyle::value (this=<optimized out>, idx=idx@entry=-15) at /usr/src/debug/musescore/MuseScore/src/engraving/style/style.cpp:51
        val = <optimized out>
        dummy = {m_type = mu::engraving::P_TYPE::UNDEFINED, m_data = std::shared_ptr<struct mu::engraving::PropertyValue::IArg> (empty) = {get() = 0x0}}
#8  0x0000555555fc019a in mu::engraving::MStyle::styleV (this=<optimized out>, idx=-15)
    at /usr/src/debug/musescore/MuseScore/src/engraving/style/style.h:52
#9  mu::engraving::EngravingObject::styleValue (this=this@entry=0x55555a325010, pid=<optimized out>, sid=-15)
    at /usr/src/debug/musescore/MuseScore/src/engraving/dom/engravingobject.cpp:770
#10 0x0000555555fc0640 in mu::engraving::EngravingObject::initElementStyle
    (this=this@entry=0x55555a325010, ss=ss@entry=0x555558c46c20 <mu::engraving::pedalStyle>)
    at /usr/src/debug/musescore/MuseScore/src/engraving/dom/engravingobject.cpp:326
        spp = @0x555558de8dc0: {sid = mu::engraving::MSQE_Sid::Sid::pedalRosetteEndText, pid = mu::engraving::Pid::END_TEXT}
        __for_range = <optimized out>
        __for_begin = Python Exception <class 'gdb.error'>: value has been optimized out
 
        __for_end = Python Exception <class 'gdb.error'>: value has been optimized out
 
        n = <optimized out>
#11 0x00005555560de833 in mu::engraving::Pedal::Pedal (this=this@entry=0x55555a325010, parent=parent@entry=0x555559788710)
    at /usr/src/debug/musescore/MuseScore/src/engraving/dom/pedal.cpp:105
```
That seems to confirm it's the same as https://github.com/musescore/MuseScore/issues/20792. So let's continue the discussion at that issue and close this one as a duplicate.

The problem is that we can't replicate this on our setups, so we can't really debug this. If you could by chance help with that, that would be hugely appreciated.
