### ISSUE TITLE
MuseScore 4.4.3 segfault at startup on Fedora 40

### ISSUE THREAD

**Issue by ycollet** [musescore/MuseScore#25307]
### Issue type

Crash or freeze

### Description with steps to reproduce

MuseScore 4.4.3 compiled from sources on Fedora 40 using gcc 14.2.1 and Qt 6.7.2

### Supporting files, videos and screenshots

The message on the console: 
```
08:05:40.638 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxUnknown
08:05:40.848 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"

08:05:40.849 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"
08:05:40.850 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"

08:05:40.850 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"
08:05:40.896 | WARN  | main_thread     | DropArea::DropArea | Dropping not implement for QtQuick on Wayland yet!
08:05:40.908 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

08:05:40.908 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
08:05:40.910 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

08:05:40.910 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
08:05:40.911 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

08:05:40.911 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
08:05:40.912 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

08:05:40.912 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
08:05:40.913 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

08:05:40.913 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
08:05:40.914 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

08:05:40.914 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
08:05:40.915 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

08:05:40.915 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
08:05:40.916 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

08:05:40.916 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
08:05:40.917 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

08:05:40.917 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
08:05:40.961 | INFO  | main_thread     | AudioOutputDeviceController::init | Available output devices changed, checking connection...
08:05:40.963 | DEBUG | main_thread     | ExtensionsLoader::loadManifestList | try load extensions, def: /usr/share/mscore-4.4//extensions, user: /home/ycollette/.local/share/MuseScore/MuseScore4Development/extensions
08:05:40.965 | DEBUG | main_thread     | ExtPluginsLoader::loadManifestList | try load extensions, def: /usr/share/mscore-4.4//plugins, user: /home/ycollette/Documents/MuseScore4Development/Plugins
08:05:40.969 | ERROR | main_thread     | ExtensionsConfiguration::manifestConfigs | failed read config data, err: [406] Une erreur s'est produite lors de la lecture du fichier, file: /home/ycollette/.local/share/MuseScore/MuseScore4Development/plugins/plugins.json
08:05:40.971 | ERROR | main_thread     | AppShellConfiguration::sessionProjectsPaths | [401] le fichier n'existe pas
08:05:41.025 | ERROR | main_thread     | Qt              | ASSERT failure in : "QObject::connect: Unique connection requires the slot to be a pointer to a member function of a QObject subclass.", file /usr/include/qt6/QtCore/qobject.h, line 256
Abandon (core dumped)
```

The gdb stack trace:
```
(gdb) where
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff4ca86d3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007ffff4c4fc4e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff4c37902 in __GI_abort () at abort.c:79
#4  0x00007ffff52cb631 in qAbort () at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/global/qglobal.cpp:161
#5  0x00007ffff5319e27 in qt_message_fatal<QString&> (context=<optimized out>, message=...) at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/global/qlogging.cpp:2025
#6  qt_message(QtMsgType, const QMessageLogContext &, const char *, typedef __va_list_tag __va_list_tag *)
    (msgType=msgType@entry=QtFatalMsg, context=..., msg=msg@entry=0x7ffff56bae18 "ASSERT failure in %s: \"%s\", file %s, line %d", ap=ap@entry=0x7fffffff71c0)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/global/qlogging.cpp:374
#7  0x00007ffff52cc4d3 in QMessageLogger::fatal (this=this@entry=0x7fffffff72a8, msg=msg@entry=0x7ffff56bae18 "ASSERT failure in %s: \"%s\", file %s, line %d")
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/global/qlogging.cpp:889
#8  0x00007ffff52cb5e1 in qt_assert_x
    (where=where@entry=0x5555575d2c50 "", what=what@entry=0x55555754f710 "QObject::connect: Unique connection requires the slot to be a pointer to a member function of a QObject subclass.", file=file@entry=0x55555754f6e8 "/usr/include/qt6/QtCore/qobject.h", line=line@entry=256) at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/global/qassert.cpp:77
#9  0x000055555582bf22 in QObject::connect<void (muse::dock::DockBase::*)(), muse::dock::DockWindow::initDocks(muse::dock::DockPageView*)::<lambda()> >
    (sender=<optimized out>, signal=(void (muse::dock::DockBase::*)(class muse::dock::DockBase * const)) 0x555556cb0f00 <muse::dock::DockBase::floatingChanged()>, context=0x555559533bd0, slot=<optimized out>, type=Qt::UniqueConnection) at /usr/include/qt6/QtCore/qobject.h:221
#10 muse::dock::DockWindow::initDocks (this=this@entry=0x555559533bd0, page=page@entry=0x5555596e3980)
    at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/src/framework/dockwindow/view/dockwindow.cpp:652
#11 0x0000555556cc3966 in muse::dock::DockWindow::doLoadPage (this=this@entry=0x555559533bd0, uri=..., params=...)
    at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/src/framework/dockwindow/view/dockwindow.cpp:502
#12 0x0000555556cc6245 in muse::dock::DockWindow::loadPage (this=0x555559533bd0, uri=..., params=...)
    at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/src/framework/dockwindow/view/dockwindow.cpp:216
#13 0x0000555556cc926f in muse::dock::DockWindow::qt_metacall (this=0x555559533bd0, _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0x7fffffff7bb8)
    at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/redhat-linux-build/src/framework/dockwindow/muse_dockwindow_autogen/OTUN7GXZT4/moc_dockwindow.cpp:227
#14 0x00007ffff71b3caa in QQmlObjectOrGadget::metacall (this=this@entry=0x7fffffff7e80, type=type@entry=QMetaObject::InvokeMetaMethod, index=<optimized out>, 
    index@entry=64, argv=<optimized out>) at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/qqmlobjectorgadget.cpp:14
#15 0x00007ffff704f1c2 in QV4::CallMethod
    (object=..., index=<optimized out>, returnType=..., argCount=<optimized out>, argTypes=<optimized out>, engine=<optimized out>, callArgs=<optimized out>, callType=<optimized out>)
    at /usr/include/qt6/QtCore/qvarlengtharray.h:84
#16 QV4::CallPrecise (object=..., data=<optimized out>, engine=<optimized out>, engine@entry=0x5555592fcaf0, callArgs=<optimized out>, 
    callArgs@entry=0x7fffcf1bf6e8, callType=callType@entry=QMetaObject::InvokeMetaMethod)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4qobjectwrapper.cpp:1950
#17 0x00007ffff7050b11 in operator() (__closure=<optimized out>) at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4qobjectwrapper.cpp:2924
#18 operator()<QV4::QObjectMethod::callInternal(const QV4::Value*, const QV4::Value*, int) const::<lambda()> > (__closure=<synthetic pointer>, call=<optimized out>)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4qobjectwrapper.cpp:2901
#19 QV4::QObjectMethod::callInternal (this=<optimized out>, thisObject=<optimized out>, argv=0x7fffcf1bf6a8, argc=2)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4qobjectwrapper.cpp:2924
--Type <RET> for more, q to quit, c to continue without paging--
#20 0x00007ffff70b0b0d in QV4::FunctionObject::call (this=<optimized out>, thisObject=<optimized out>, argv=<optimized out>, argc=<optimized out>)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4functionobject_p.h:171
#21 QV4::Moth::VME::interpret (frame=0x3d12, frame@entry=0x7fffffff8180, engine=0x5555592fcaf0, code=0x7fffcf1bf690 "\300\f\346\316\377\177")
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4vme_moth.cpp:798
#22 0x00007ffff70b2edf in QV4::Moth::VME::exec (frame=frame@entry=0x7fffffff8180, engine=engine@entry=0x5555592fcaf0)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4vme_moth.cpp:487
#23 0x00007ffff6ff2646 in QV4::doCall (self=<optimized out>, thisObject=thisObject@entry=0x7fffcf1bf630, argv=<optimized out>, argc=argc@entry=2, context=<optimized out>)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4function.cpp:54
#24 0x00007ffff6ff2b4d in QV4::Function::call
    (this=this@entry=0x555559530e90, thisObject=0x7fffcf1bf630, argv=argv@entry=0x7fffcf1bf630, argc=argc@entry=2, context=context@entry=0x7fffe0002af0)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4function.cpp:79
#25 0x00007ffff6ff2e79 in operator() (__closure=<synthetic pointer>, thisObject=<optimized out>, argv=0x7fffcf1bf630, argc=2)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4function.cpp:30
#26 QV4::convertAndCall<QV4::Function::call(QObject*, void**, const QMetaType*, int, QV4::ExecutionContext*)::<lambda(const QV4::Value*, const QV4::Value*, int)> >
    (engine=<optimized out>, thisObject=0x55555ae9a720, a=0x7fffffffa368, types=0x7fffffff8498, argc=2, call=...)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4jscall_p.h:202
#27 QV4::Function::call (this=0x555559530e90, thisObject=0x55555ae9a720, a=a@entry=0x7fffffffa368, types=0x7fffffff8498, argc=2, context=0x7fffe0002af0)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4function.cpp:27
#28 0x00007ffff716e2d7 in QQmlJavaScriptExpression::evaluate (this=this@entry=0x55555ae9b1e0, a=a@entry=0x7fffffffa368, types=<optimized out>, argc=argc@entry=2)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/qqmljavascriptexpression_p.h:248
#29 0x00007ffff710bcad in QQmlBoundSignalExpression::evaluate (this=0x55555ae9b1e0, a=a@entry=0x7fffffffa368) at /usr/include/qt6/QtCore/qvarlengtharray.h:85
#30 0x00007ffff710c800 in QQmlBoundSignal_callback (e=0x55555ae7e1f0, a=0x7fffffffa368) at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/ftw/qqmlrefcount_p.h:73
#31 0x00007ffff719d195 in QQmlNotifier::emitNotify (endpoint=<optimized out>, a=0x7fffffffa368) at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/qqmlnotifier.cpp:70
#32 0x00007ffff53fc42d in doActivate<false> (sender=0x55555ae9a720, signal_index=36, argv=argv@entry=0x7fffffffa368)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qobject.cpp:3976
#33 0x00007ffff53f321f in QMetaObject::activate (sender=<optimized out>, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=argv@entry=0x7fffffffa368)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qobject.cpp:4159
#34 0x00007ffff72662df in QQmlVMEMetaObject::activate (this=this@entry=0x55555ae9a9b0, object=<optimized out>, index=index@entry=62, args=args@entry=0x7fffffffa368)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/qqmlvmemetaobject.cpp:1467
#35 0x00007ffff726869b in QQmlVMEMetaObject::metaCall (this=0x55555ae9a9b0, o=<optimized out>, c=QMetaObject::InvokeMetaMethod, _id=62, a=0x7fffffffa368)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/qqmlvmemetaobject.cpp:1121
#36 0x00007ffff71b3caa in QQmlObjectOrGadget::metacall (this=this@entry=0x7fffffffa630, type=type@entry=QMetaObject::InvokeMetaMethod, index=<optimized out>, 
    index@entry=62, argv=<optimized out>) at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/qqmlobjectorgadget.cpp:14
#37 0x00007ffff704f1c2 in QV4::CallMethod
    (object=..., index=<optimized out>, returnType=..., argCount=<optimized out>, argTypes=<optimized out>, engine=<optimized out>, callArgs=<optimized out>, callType=<optimized out>)
    at /usr/include/qt6/QtCore/qvarlengtharray.h:84
#38 QV4::CallPrecise (object=..., data=<optimized out>, engine=<optimized out>, engine@entry=0x5555592fcaf0, callArgs=<optimized out>, 
    callArgs@entry=0x7fffcf1bf5e8, callType=callType@entry=QMetaObject::InvokeMetaMethod)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4qobjectwrapper.cpp:1950
#39 0x00007ffff7050b11 in operator() (__closure=<optimized out>) at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4qobjectwrapper.cpp:2924
#40 operator()<QV4::QObjectMethod::callInternal(const QV4::Value*, const QV4::Value*, int) const::<lambda()> > (__closure=<synthetic pointer>, call=<optimized out>)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4qobjectwrapper.cpp:2901
#41 QV4::QObjectMethod::callInternal (this=<optimized out>, thisObject=<optimized out>, argv=0x7fffcf1bf580, argc=2)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4qobjectwrapper.cpp:2924
#42 0x00007ffff70b0b0d in QV4::FunctionObject::call (this=<optimized out>, thisObject=<optimized out>, argv=<optimized out>, argc=<optimized out>)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4functionobject_p.h:171
#43 QV4::Moth::VME::interpret (frame=0x3d12, frame@entry=0x7fffffffa930, engine=0x5555592fcaf0, code=0x7fffcf1bf568 "\340q\351\316\377\177")
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4vme_moth.cpp:798
#44 0x00007ffff70b2edf in QV4::Moth::VME::exec (frame=frame@entry=0x7fffffffa930, engine=engine@entry=0x5555592fcaf0)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4vme_moth.cpp:487
#45 0x00007ffff6ff2646 in QV4::doCall (self=<optimized out>, thisObject=thisObject@entry=0x7fffcf1bf4f0, argv=<optimized out>, argc=argc@entry=1, context=<optimized out>)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4function.cpp:54
#46 0x00007ffff6ff2b4d in QV4::Function::call
    (this=this@entry=0x55555ae9a2d0, thisObject=0x7fffcf1bf4f0, argv=argv@entry=0x7fffcf1bf4f0, argc=argc@entry=1, context=context@entry=0x7fffe0002058)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4function.cpp:79
#47 0x00007ffff6ff2e79 in operator() (__closure=<synthetic pointer>, thisObject=<optimized out>, argv=0x7fffcf1bf4f0, argc=1)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4function.cpp:30
#48 QV4::convertAndCall<QV4::Function::call(QObject*, void**, const QMetaType*, int, QV4::ExecutionContext*)::<lambda(const QV4::Value*, const QV4::Value*, int)> >
    (engine=<optimized out>, thisObject=0x55555ae9b2f0, a=0x7fffffffc6e0, types=0x7fffffffac48, argc=1, call=...)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4jscall_p.h:202
#49 QV4::Function::call (this=0x55555ae9a2d0, thisObject=0x55555ae9b2f0, a=a@entry=0x7fffffffc6e0, types=0x7fffffffac48, argc=1, context=0x7fffe0002058)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/jsruntime/qv4function.cpp:27
#50 0x00007ffff716e2d7 in QQmlJavaScriptExpression::evaluate (this=this@entry=0x55555af11760, a=a@entry=0x7fffffffc6e0, types=<optimized out>, argc=argc@entry=1)
    at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/qqmljavascriptexpression_p.h:248
#51 0x00007ffff710bcad in QQmlBoundSignalExpression::evaluate (this=0x55555af11760, a=a@entry=0x7fffffffc6e0) at /usr/include/qt6/QtCore/qvarlengtharray.h:85
#52 0x00007ffff710c800 in QQmlBoundSignal_callback (e=0x55555af11710, a=0x7fffffffc6e0) at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/ftw/qqmlrefcount_p.h:73
#53 0x00007ffff719d195 in QQmlNotifier::emitNotify (endpoint=<optimized out>, a=0x7fffffffc6e0) at /usr/src/debug/qt6-qtdeclarative-6.7.2-2.fc40.x86_64/src/qml/qml/qqmlnotifier.cpp:70
#54 0x00007ffff53fc42d in doActivate<false> (sender=0x55555946f5b0, signal_index=3, argv=0x7fffffffc6e0)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qobject.cpp:3976
#55 0x00007ffff53f2bc7 in QMetaObject::activate
    (sender=sender@entry=0x55555946f5b0, m=m@entry=0x555558d01480 <muse::ui::InteractiveProvider::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffc6e0) at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qobject.cpp:4146
#56 0x0000555556c0553e in muse::ui::InteractiveProvider::fireOpen (this=this@entry=0x55555946f5b0, _t1=<optimized out>, _t1@entry=0x555559254fc0)
    at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/redhat-linux-build/src/framework/ui/muse_ui_autogen/OTUN7GXZT4/moc_interactiveprovider.cpp:407
#57 0x0000555556bf0f14 in muse::ui::InteractiveProvider::openQml (this=this@entry=0x55555946f5b0, q=...)
    at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/src/framework/ui/view/interactiveprovider.cpp:708
--Type <RET> for more, q to quit, c to continue without paging--
#58 0x0000555556bf6943 in muse::ui::InteractiveProvider::open (this=0x55555946f5b0, q=...)
    at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/src/framework/ui/view/interactiveprovider.cpp:240
#59 0x0000555555df63fc in muse::Interactive::open (this=this@entry=0x5555591dcbd0, uri=...)
    at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/src/framework/global/internal/interactive.cpp:266
#60 0x0000555555df168d in muse::Interactive::open (this=0x5555591dcbd0, uri=<optimized out>)
    at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/src/framework/global/internal/interactive.cpp:256
#61 0x0000555556d37492 in mu::appshell::StartupScenario::run (this=0x55555932d5c0) at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/src/appshell/internal/startupscenario.cpp:119
#62 0x00007ffff53eddcb in QObject::event (this=0x5555591b8740, e=0x55555c9fe0f0) at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qobject.cpp:1452
#63 0x00007ffff658b218 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x5555591b8740, e=0x55555c9fe0f0)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/widgets/kernel/qapplication.cpp:3287
#64 0x00007ffff5396e88 in QCoreApplication::notifyInternal2 (receiver=0x5555591b8740, event=0x55555c9fe0f0)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1142
#65 0x00007ffff53970ed in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1583
#66 0x00007ffff539ac51 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x55555915f110)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1940
#67 0x00007ffff539aefd in QCoreApplication::sendPostedEvents (receiver=<optimized out>, event_type=<optimized out>)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qcoreapplication.cpp:1797
#68 0x00007ffff56859ef in postEventSourceDispatch (s=0x5555592ee870) at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qeventdispatcher_glib.cpp:244
#69 0x00007ffff3fd5e8c in g_main_dispatch (context=0x7fffdc000f00) at ../glib/gmain.c:3344
#70 g_main_context_dispatch_unlocked (context=0x7fffdc000f00) at ../glib/gmain.c:4152
#71 0x00007ffff4037c98 in g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffdc000f00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:4217
#72 0x00007ffff3fd7383 in g_main_context_iteration (context=0x7fffdc000f00, may_block=1) at ../glib/gmain.c:4282
#73 0x00007ffff56851a3 in QEventDispatcherGlib::processEvents (this=0x5555591cca10, flags=...)
    at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/kernel/qeventdispatcher_glib.cpp:394
#74 0x00007ffff53a3bc3 in QEventLoop::exec (this=this@entry=0x7fffffffd3c0, flags=..., flags@entry=...) at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/global/qflags.h:34
#75 0x00007ffff539fa7c in QCoreApplication::exec () at /usr/src/debug/qt6-qtbase-6.7.2-6.fc40.x86_64/src/corelib/global/qflags.h:74
#76 0x00005555559322e8 in main (argc=<optimized out>, argv=0x7fffffffda18) at /usr/src/debug/mscore-mao-4.4.3-3.fc40.x86_64/src/app/main.cpp:200
```

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3

### Regression

No.

### Operating system

Fedora 40

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Eism** [comment]
@ycollet 
At the moment, we support Qt 6.2.4, and there are no problems with the build. It is recommended that you build on this version.

**Comment by ycollet** [comment]
You can find here a various set of patches which make 4.3.2 works on Fedora 41 ...
https://src.fedoraproject.org/rpms/musescore/tree/rawhide
